services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: taskmanager
      POSTGRES_PASSWORD: "P@ssw0rd!2026SecureDB"
      POSTGRES_DB: taskmanager_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U taskmanager"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    image: saikiranasamwar4/taskmanager-backend
    environment:
      - FLASK_ENV=production
      - SECRET_KEY=7a8f9d2e4c6b1a3e5d7f9b2c4e6a8d0f1c3e5a7b9d1f3e5c7a9b1d3f5e7a9c1b
      - DATABASE_URL=postgresql://taskmanager:P%40ssw0rd%212026SecureDB@postgres:5432/taskmanager_db
    volumes:
      - backend_instance:/app/instance
    ports:
      - "8888:8888"
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    build: ./frontend
    image: saikiranasamwar4/taskmanager-frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  postgres_data:
  backend_instance:
