services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: taskmanager
      POSTGRES_PASSWORD: "P@ssw0rd!2026SecureDB"
      POSTGRES_DB: taskmanager_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    image: saikiranasamwar4/taskmanager-backend
    environment:
      - FLASK_ENV=production
      - SECRET_KEY=7a8f9d2e4c6b1a3e5d7f9b2c4e6a8d0f1c3e5a7b9d1f3e5c7a9b1d3f5e7a9c1b
      - DATABASE_URL=postgresql://taskmanager:P@ssw0rd!2026SecureDB@postgres:5432/taskmanager_db
    volumes:
      - ./backend:/app
      - backend_instance:/app/instance
    ports:
      - "8888:8888"
    depends_on:
      - postgres

  frontend:
    image: saikiranasamwar4/taskmanager-frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  postgres_data:
  backend_instance:
